package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "AnObject")
public class AnObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "myDataAttribute")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer myDataAttribute;

    @org.kie.api.definition.type.Label(value = "myDataAttribute2")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String myDataAttribute2;

    public AnObject() {
    }
    
    public AnObject(java.lang.Integer myDataAttribute, java.lang.String myDataAttribute2) {
        this.myDataAttribute = myDataAttribute;
        this.myDataAttribute2 = myDataAttribute2;
    }

    public java.lang.Integer getMyDataAttribute() {
        return this.myDataAttribute;
    }
    
    public void setMyDataAttribute(java.lang.Integer myDataAttribute) {
        this.myDataAttribute = myDataAttribute;
    }

    public java.lang.String getMyDataAttribute2() {
        return this.myDataAttribute2;
    }
    
    public void setMyDataAttribute2(java.lang.String myDataAttribute2) {
        this.myDataAttribute2 = myDataAttribute2;
    }

}