package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "ApplicantData")
public class ApplicantData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "age")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer age;

    @org.kie.api.definition.type.Label(value = "employmentStatus")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String employmentStatus;

    @org.kie.api.definition.type.Label(value = "isExistingCustomer")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean isExistingCustomer;

    @org.kie.api.definition.type.Label(value = "maritalStatus")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String maritalStatus;

    @org.kie.api.definition.type.Label(value = "monthlyExpenses")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Double monthlyExpenses;

    @org.kie.api.definition.type.Label(value = "monthlyIncome")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Double monthlyIncome;

    @org.kie.api.definition.type.Label(value = "monthlyRepayments")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Double monthlyRepayments;

    public ApplicantData() {
    }
    
    public ApplicantData(java.lang.Integer age, java.lang.Boolean isExistingCustomer, java.lang.String maritalStatus, java.lang.String employmentStatus, java.lang.Double monthlyIncome, java.lang.Double monthlyRepayments, java.lang.Double monthlyExpenses) {
        this.age = age;
        this.isExistingCustomer = isExistingCustomer;
        this.maritalStatus = maritalStatus;
        this.employmentStatus = employmentStatus;
        this.monthlyIncome = monthlyIncome;
        this.monthlyRepayments = monthlyRepayments;
        this.monthlyExpenses = monthlyExpenses;
    }

    public java.lang.Integer getAge() {
        return this.age;
    }
    
    public void setAge(java.lang.Integer age) {
        this.age = age;
    }

    public java.lang.String getEmploymentStatus() {
        return this.employmentStatus;
    }
    
    public void setEmploymentStatus(java.lang.String employmentStatus) {
        this.employmentStatus = employmentStatus;
    }

    public java.lang.Boolean getIsExistingCustomer() {
        return this.isExistingCustomer;
    }
    
    public void setIsExistingCustomer(java.lang.Boolean isExistingCustomer) {
        this.isExistingCustomer = isExistingCustomer;
    }

    public java.lang.String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(java.lang.String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public java.lang.Double getMonthlyExpenses() {
        return this.monthlyExpenses;
    }
    
    public void setMonthlyExpenses(java.lang.Double monthlyExpenses) {
        this.monthlyExpenses = monthlyExpenses;
    }

    public java.lang.Double getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(java.lang.Double monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    public java.lang.Double getMonthlyRepayments() {
        return this.monthlyRepayments;
    }
    
    public void setMonthlyRepayments(java.lang.Double monthlyRepayments) {
        this.monthlyRepayments = monthlyRepayments;
    }

}