package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "BureauData")
public class BureauData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "bankrupt")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Boolean bankrupt;

    @org.kie.api.definition.type.Label(value = "creditScore")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer creditScore;

    public BureauData() {
    }
    
    public BureauData(java.lang.Boolean bankrupt, java.lang.Integer creditScore) {
        this.bankrupt = bankrupt;
        this.creditScore = creditScore;
    }

    public java.lang.Boolean getBankrupt() {
        return this.bankrupt;
    }
    
    public void setBankrupt(java.lang.Boolean bankrupt) {
        this.bankrupt = bankrupt;
    }

    public java.lang.Integer getCreditScore() {
        return this.creditScore;
    }
    
    public void setCreditScore(java.lang.Integer creditScore) {
        this.creditScore = creditScore;
    }

}