package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "InstallmentCalculation")
public class InstallmentCalculation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "monthlyFee")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Double monthlyFee;

    @org.kie.api.definition.type.Label(value = "monthlyRepayment")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Double monthlyRepayment;

    public InstallmentCalculation() {
    }
    
    public InstallmentCalculation(java.lang.Double monthlyFee, java.lang.Double monthlyRepayment) {
        this.monthlyFee = monthlyFee;
        this.monthlyRepayment = monthlyRepayment;
    }

    public java.lang.Double getMonthlyFee() {
        return this.monthlyFee;
    }
    
    public void setMonthlyFee(java.lang.Double monthlyFee) {
        this.monthlyFee = monthlyFee;
    }

    public java.lang.Double getMonthlyRepayment() {
        return this.monthlyRepayment;
    }
    
    public void setMonthlyRepayment(java.lang.Double monthlyRepayment) {
        this.monthlyRepayment = monthlyRepayment;
    }

}