package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "LogicContext")
public class LogicContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "bureauCallType")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String bureauCallType;

    @org.kie.api.definition.type.Label(value = "routing")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String routing;

    @org.kie.api.definition.type.Label(value = "strategy")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String strategy;

    public LogicContext() {
    }
    
    public LogicContext(java.lang.String strategy, java.lang.String bureauCallType, java.lang.String routing) {
        this.strategy = strategy;
        this.bureauCallType = bureauCallType;
        this.routing = routing;
    }

    public java.lang.String getBureauCallType() {
        return this.bureauCallType;
    }
    
    public void setBureauCallType(java.lang.String bureauCallType) {
        this.bureauCallType = bureauCallType;
    }

    public java.lang.String getRouting() {
        return this.routing;
    }
    
    public void setRouting(java.lang.String routing) {
        this.routing = routing;
    }

    public java.lang.String getStrategy() {
        return this.strategy;
    }
    
    public void setStrategy(java.lang.String strategy) {
        this.strategy = strategy;
    }

}