package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("LogicContext")
public class LogicContext implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("bureauCallType")
   @org.kie.api.definition.type.Position(1)
   private java.lang.String bureauCallType;

   @org.kie.api.definition.type.Label("routing")
   @org.kie.api.definition.type.Position(2)
   private java.lang.String routing;

   @org.kie.api.definition.type.Label("strategy")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String strategy;

   @org.kie.api.definition.type.Label(value = "eligibility")
   @org.kie.api.definition.type.Position(value = 3)
   private java.lang.String eligibility;

   public java.lang.String getBureauCallType()
   {
      return this.bureauCallType;
   }

   public void setBureauCallType(java.lang.String bureauCallType)
   {
      this.bureauCallType = bureauCallType;
   }

   public java.lang.String getRouting()
   {
      return this.routing;
   }

   public void setRouting(java.lang.String routing)
   {
      this.routing = routing;
   }

   public java.lang.String getStrategy()
   {
      return this.strategy;
   }

   public void setStrategy(java.lang.String strategy)
   {
      this.strategy = strategy;
   }

   public java.lang.String getEligibility()
   {
      return this.eligibility;
   }

   public void setEligibility(java.lang.String eligibility)
   {
      this.eligibility = eligibility;
   }

   public LogicContext()
   {
   }

   public LogicContext(java.lang.String strategy,
         java.lang.String bureauCallType, java.lang.String routing,
         java.lang.String eligibility)
   {
      this.strategy = strategy;
      this.bureauCallType = bureauCallType;
      this.routing = routing;
      this.eligibility = eligibility;
   }

}