package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "PartialApplication")
public class PartialApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "partialScore")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer partialScore;

    public PartialApplication() {
    }
    
    public PartialApplication(java.lang.Integer partialScore) {
        this.partialScore = partialScore;
    }

    public java.lang.Integer getPartialScore() {
        return this.partialScore;
    }
    
    public void setPartialScore(java.lang.Integer partialScore) {
        this.partialScore = partialScore;
    }

}