package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PreBureauData")
public class PreBureauData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("affordability")
   @org.kie.api.definition.type.Position(1)
   private java.lang.Boolean affordability;

   @org.kie.api.definition.type.Label("riskCategory")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String riskCategory;

   @org.kie.api.definition.type.Label(value = "creditContingencyFactor")
   @org.kie.api.definition.type.Position(value = 2)
   private java.lang.Double creditContingencyFactor;

   public java.lang.Boolean getAffordability()
   {
      return this.affordability;
   }

   public void setAffordability(java.lang.Boolean affordability)
   {
      this.affordability = affordability;
   }

   public java.lang.String getRiskCategory()
   {
      return this.riskCategory;
   }

   public void setRiskCategory(java.lang.String riskCategory)
   {
      this.riskCategory = riskCategory;
   }

   public java.lang.Double getCreditContingencyFactor()
   {
      return this.creditContingencyFactor;
   }

   public void setCreditContingencyFactor(
         java.lang.Double creditContingencyFactor)
   {
      this.creditContingencyFactor = creditContingencyFactor;
   }

   public PreBureauData()
   {
   }

   public PreBureauData(java.lang.String riskCategory,
         java.lang.Boolean affordability,
         java.lang.Double creditContingencyFactor)
   {
      this.riskCategory = riskCategory;
      this.affordability = affordability;
      this.creditContingencyFactor = creditContingencyFactor;
   }

}