package com.decisionmanagementsolutions.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "RequestedProduct")
public class RequestedProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "amount")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Double amount;

    @org.kie.api.definition.type.Label(value = "productType")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String productType;

    @org.kie.api.definition.type.Label(value = "rate")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Double rate;

    @org.kie.api.definition.type.Label(value = "term")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer term;

    public RequestedProduct() {
    }
    
    public RequestedProduct(java.lang.String productType, java.lang.Double rate, java.lang.Integer term, java.lang.Double amount) {
        this.productType = productType;
        this.rate = rate;
        this.term = term;
        this.amount = amount;
    }

    public java.lang.Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.lang.Double amount) {
        this.amount = amount;
    }

    public java.lang.String getProductType() {
        return this.productType;
    }
    
    public void setProductType(java.lang.String productType) {
        this.productType = productType;
    }

    public java.lang.Double getRate() {
        return this.rate;
    }
    
    public void setRate(java.lang.Double rate) {
        this.rate = rate;
    }

    public java.lang.Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(java.lang.Integer term) {
        this.term = term;
    }

}